server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flight_db
    # --- Replace with your local DB credentials:
    username: 
    password: 
    # ------------------------------------------
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html